>动态规划Python版
$$d[i,j]=\left\{\begin{array}{cc} 
		d[i-1,j-1], &S_1(i)=S_2(j)\\ 
		min\left\{\begin{array}{cc} 
		d[i,j-1]+1, \\ 
		d[i-1,j]+1, \\
        d[i-1,j-1]+1,
	       \end{array}\right.&S_1(i)≠S_2(j)\\
	\end{array}\right.$$


如果只S1(i)=S2(j),那么只需要考1虑S1的前i-1个字符与S2的前j-1个字符。
否则：
考虑其他三种操作，d[i,j-1]+1，末尾插入。
d[i-1,j]+1，删除。
d[i-1,j-1]+1，修改。

In [48]:
#S1的字符串长度为n1,S2的字符串长度为n2。
import numpy as np
def geteditlength(s1,s2):
    n1=len(s1)
    n2=len(s2)
    d = np.empty(shape=(n1+1,n2+1))
    for j in range(0,n2+1):
        d[0,j]=j
    for i in range(n1):
        d[i+1,0]=i+1
        for j in range(n2):
            if s1[i]==s2[j]:
                d[i+1,j+1]=d[i,j]
            else:
                d[i+1,j+1]=min([d[i+1,j],d[i,j+1],d[i,j]])+1
    return d
s1 = [i for i in 'math']
s2=[j for j in 'mouth']
print(geteditlength(s1,s2))

[[ 0.  1.  2.  3.  4.  5.]
 [ 1.  0.  1.  2.  3.  4.]
 [ 2.  1.  1.  2.  3.  4.]
 [ 3.  2.  2.  2.  2.  3.]
 [ 4.  3.  3.  3.  3.  2.]]


In [56]:
#滚动数组优化(Sliding Array)
import numpy as np
def sliding(s1,s2):
    n1=len(s1)
    n2=len(s2)
    dold = np.empty(n2+1)
    print(dold)
    dnew=np.empty(n2+1)
    for j in range(0,n2+1):
        dold[j] = j
    for i in range(n1):
        dnew[0]=i
        for j in range(n2):
            if s1[i]==s2[j]:
                dnew[j+1]==dold[j]
            else:  
                dnew[j+1]=min([dnew[j],dold[j+1],dold[j]])+1
        dnew,dold =dold,dnew
    return dnew
s1 = [i for i in 'math']
s2=[j for j in 'mouth']
print(sliding(s1,s2))
    

[ 2.  2.  2.  3.  4.  5.]
[ 2.  2.  2.  3.  4.  5.]
